export interface TopicNode {
  id: string;
  label: string;
  ring: number;
  angle: number;
  sz: 'lg' | 'md' | 'sm';
}

export const TOPICS: TopicNode[] = [
  { id: 'ai', label: 'AI', ring: 1, angle: 0.00, sz: 'lg' },
  { id: 'programming', label: 'Programming', ring: 1, angle: 0.52, sz: 'lg' },
  { id: 'web', label: 'Web', ring: 1, angle: 1.05, sz: 'lg' },
  { id: 'data', label: 'Data', ring: 1, angle: 1.57, sz: 'lg' },
  { id: 'cloud', label: 'Cloud', ring: 1, angle: 2.09, sz: 'lg' },
  { id: 'security', label: 'Security', ring: 1, angle: 2.62, sz: 'lg' },
  { id: 'mobile', label: 'Mobile', ring: 1, angle: 3.14, sz: 'lg' },
  { id: 'design', label: 'Design', ring: 1, angle: 3.67, sz: 'lg' },
  { id: 'devops', label: 'DevOps', ring: 1, angle: 4.19, sz: 'lg' },
  { id: 'science', label: 'Science', ring: 1, angle: 4.71, sz: 'lg' },
  { id: 'math', label: 'Math', ring: 1, angle: 5.24, sz: 'lg' },
  { id: 'hardware', label: 'Hardware', ring: 1, angle: 5.76, sz: 'lg' },
  { id: 'machine-learning', label: 'Machine Learning', ring: 2, angle: 0.00, sz: 'md' },
  { id: 'deep-learning', label: 'Deep Learning', ring: 2, angle: 0.31, sz: 'md' },
  { id: 'nlp', label: 'NLP', ring: 2, angle: 0.63, sz: 'md' },
  { id: 'computer-vision', label: 'Computer Vision', ring: 2, angle: 0.94, sz: 'md' },
  { id: 'generative-ai', label: 'Generative AI', ring: 2, angle: 1.26, sz: 'md' },
  { id: 'llm', label: 'LLMs', ring: 2, angle: 1.57, sz: 'md' },
  { id: 'python', label: 'Python', ring: 2, angle: 1.88, sz: 'md' },
  { id: 'javascript', label: 'JavaScript', ring: 2, angle: 2.20, sz: 'md' },
  { id: 'typescript', label: 'TypeScript', ring: 2, angle: 2.51, sz: 'md' },
  { id: 'rust', label: 'Rust', ring: 2, angle: 2.83, sz: 'md' },
  { id: 'go', label: 'Go', ring: 2, angle: 3.14, sz: 'md' },
  { id: 'java', label: 'Java', ring: 2, angle: 3.46, sz: 'md' },
  { id: 'react', label: 'React', ring: 2, angle: 3.77, sz: 'md' },
  { id: 'nextjs', label: 'Next.js', ring: 2, angle: 4.08, sz: 'md' },
  { id: 'nodejs', label: 'Node.js', ring: 2, angle: 4.40, sz: 'md' },
  { id: 'sql', label: 'SQL', ring: 2, angle: 4.71, sz: 'md' },
  { id: 'mongodb', label: 'MongoDB', ring: 2, angle: 5.03, sz: 'md' },
  { id: 'docker', label: 'Docker', ring: 2, angle: 5.34, sz: 'md' },
  { id: 'kubernetes', label: 'Kubernetes', ring: 2, angle: 5.65, sz: 'md' },
  { id: 'aws', label: 'AWS', ring: 2, angle: 5.97, sz: 'md' },
  { id: 'transformers', label: 'Transformers', ring: 3, angle: 0.00, sz: 'sm' },
  { id: 'gpt', label: 'GPT', ring: 3, angle: 0.22, sz: 'sm' },
  { id: 'chatgpt', label: 'ChatGPT', ring: 3, angle: 0.44, sz: 'sm' },
  { id: 'claude', label: 'Claude', ring: 3, angle: 0.66, sz: 'sm' },
  { id: 'gemini-ai', label: 'Gemini', ring: 3, angle: 0.88, sz: 'sm' },
  { id: 'llama', label: 'LLaMA', ring: 3, angle: 1.10, sz: 'sm' },
  { id: 'neural-networks', label: 'Neural Networks', ring: 3, angle: 1.32, sz: 'sm' },
  { id: 'reinforcement-learning', label: 'RL', ring: 3, angle: 1.54, sz: 'sm' },
  { id: 'csharp', label: 'C#', ring: 3, angle: 1.76, sz: 'sm' },
  { id: 'cpp', label: 'C++', ring: 3, angle: 1.98, sz: 'sm' },
  { id: 'swift', label: 'Swift', ring: 3, angle: 2.20, sz: 'sm' },
  { id: 'kotlin', label: 'Kotlin', ring: 3, angle: 2.42, sz: 'sm' },
  { id: 'vue', label: 'Vue', ring: 3, angle: 2.64, sz: 'sm' },
  { id: 'svelte', label: 'Svelte', ring: 3, angle: 2.86, sz: 'sm' },
  { id: 'html', label: 'HTML', ring: 3, angle: 3.08, sz: 'sm' },
  { id: 'css', label: 'CSS', ring: 3, angle: 3.30, sz: 'sm' },
  { id: 'tailwind', label: 'Tailwind', ring: 3, angle: 3.52, sz: 'sm' },
  { id: 'postgresql', label: 'PostgreSQL', ring: 3, angle: 3.74, sz: 'sm' },
  { id: 'redis', label: 'Redis', ring: 3, angle: 3.96, sz: 'sm' },
  { id: 'firebase', label: 'Firebase', ring: 3, angle: 4.18, sz: 'sm' },
  { id: 'terraform', label: 'Terraform', ring: 3, angle: 4.40, sz: 'sm' },
  { id: 'ci-cd', label: 'CI/CD', ring: 3, angle: 4.62, sz: 'sm' },
  { id: 'github-actions', label: 'GitHub Actions', ring: 3, angle: 4.84, sz: 'sm' },
  { id: 'cryptography', label: 'Cryptography', ring: 3, angle: 5.06, sz: 'sm' },
  { id: 'encryption', label: 'Encryption', ring: 3, angle: 5.28, sz: 'sm' },
  { id: 'oauth', label: 'OAuth', ring: 3, angle: 5.50, sz: 'sm' },
  { id: 'pen-testing', label: 'Pen Testing', ring: 3, angle: 5.72, sz: 'sm' },
  { id: 'zero-trust', label: 'Zero Trust', ring: 3, angle: 5.94, sz: 'sm' },
  { id: 'statistics', label: 'Statistics', ring: 4, angle: 0.00, sz: 'sm' },
  { id: 'linear-algebra', label: 'Linear Algebra', ring: 4, angle: 0.20, sz: 'sm' },
  { id: 'calculus', label: 'Calculus', ring: 4, angle: 0.40, sz: 'sm' },
  { id: 'probability', label: 'Probability', ring: 4, angle: 0.60, sz: 'sm' },
  { id: 'algorithms', label: 'Algorithms', ring: 4, angle: 0.80, sz: 'sm' },
  { id: 'data-structures', label: 'Data Structures', ring: 4, angle: 1.00, sz: 'sm' },
  { id: 'compilers', label: 'Compilers', ring: 4, angle: 1.20, sz: 'sm' },
  { id: 'operating-systems', label: 'OS', ring: 4, angle: 1.40, sz: 'sm' },
  { id: 'physics', label: 'Physics', ring: 4, angle: 1.60, sz: 'sm' },
  { id: 'quantum', label: 'Quantum', ring: 4, angle: 1.80, sz: 'sm' },
  { id: 'biology', label: 'Biology', ring: 4, angle: 2.00, sz: 'sm' },
  { id: 'neuroscience', label: 'Neuroscience', ring: 4, angle: 2.20, sz: 'sm' },
  { id: 'chemistry', label: 'Chemistry', ring: 4, angle: 2.40, sz: 'sm' },
  { id: 'robotics', label: 'Robotics', ring: 4, angle: 2.60, sz: 'sm' },
  { id: 'iot', label: 'IoT', ring: 4, angle: 2.80, sz: 'sm' },
  { id: 'embedded', label: 'Embedded', ring: 4, angle: 3.00, sz: 'sm' },
  { id: 'fpga', label: 'FPGA', ring: 4, angle: 3.20, sz: 'sm' },
  { id: 'ui-ux', label: 'UI/UX', ring: 4, angle: 3.40, sz: 'sm' },
  { id: 'figma', label: 'Figma', ring: 4, angle: 3.60, sz: 'sm' },
  { id: 'design-systems', label: 'Design Systems', ring: 4, angle: 3.80, sz: 'sm' },
  { id: 'accessibility', label: 'Accessibility', ring: 4, angle: 4.00, sz: 'sm' },
  { id: 'ethereum', label: 'Ethereum', ring: 4, angle: 4.20, sz: 'sm' },
  { id: 'web3', label: 'Web3', ring: 4, angle: 4.40, sz: 'sm' },
  { id: 'defi', label: 'DeFi', ring: 4, angle: 4.60, sz: 'sm' },
  { id: 'smart-contracts', label: 'Smart Contracts', ring: 4, angle: 4.80, sz: 'sm' },
  { id: 'ios', label: 'iOS', ring: 4, angle: 5.00, sz: 'sm' },
  { id: 'android', label: 'Android', ring: 4, angle: 5.20, sz: 'sm' },
  { id: 'react-native', label: 'React Native', ring: 4, angle: 5.40, sz: 'sm' },
  { id: 'flutter', label: 'Flutter', ring: 4, angle: 5.60, sz: 'sm' },
  { id: 'unity', label: 'Unity', ring: 4, angle: 5.80, sz: 'sm' },
  { id: 'unreal', label: 'Unreal', ring: 4, angle: 6.00, sz: 'sm' },
  { id: 'godot', label: 'Godot', ring: 4, angle: 6.20, sz: 'sm' },
  { id: 'git', label: 'Git', ring: 4, angle: 0.10, sz: 'sm' },
  { id: 'github', label: 'GitHub', ring: 4, angle: 0.30, sz: 'sm' },
  { id: 'linux', label: 'Linux', ring: 4, angle: 0.50, sz: 'sm' },
  { id: 'tdd', label: 'TDD', ring: 4, angle: 0.70, sz: 'sm' },
  { id: 'playwright', label: 'Playwright', ring: 4, angle: 0.90, sz: 'sm' },
  { id: 'jest', label: 'Jest', ring: 4, angle: 1.10, sz: 'sm' },
  { id: 'cypress', label: 'Cypress', ring: 4, angle: 1.30, sz: 'sm' },
  { id: 'spark', label: 'Spark', ring: 4, angle: 1.50, sz: 'sm' },
  { id: 'kafka', label: 'Kafka', ring: 4, angle: 1.70, sz: 'sm' },
  { id: 'airflow', label: 'Airflow', ring: 4, angle: 1.90, sz: 'sm' },
  { id: 'data-engineering', label: 'Data Engineering', ring: 4, angle: 2.10, sz: 'sm' },
  { id: 'microservices', label: 'Microservices', ring: 4, angle: 2.30, sz: 'sm' },
  { id: 'serverless', label: 'Serverless', ring: 4, angle: 2.50, sz: 'sm' },
  { id: 'event-driven', label: 'Event-Driven', ring: 4, angle: 2.70, sz: 'sm' },
  { id: 'tls', label: 'TLS', ring: 4, angle: 2.90, sz: 'sm' },
  { id: 'websockets', label: 'WebSockets', ring: 4, angle: 3.10, sz: 'sm' },
  { id: 'http', label: 'HTTP', ring: 4, angle: 3.30, sz: 'sm' },
  { id: 'dns', label: 'DNS', ring: 4, angle: 3.50, sz: 'sm' },
  { id: 'interviews', label: 'Interviews', ring: 4, angle: 3.70, sz: 'sm' },
  { id: 'portfolio', label: 'Portfolio', ring: 4, angle: 3.90, sz: 'sm' },
  { id: 'freelancing', label: 'Freelancing', ring: 4, angle: 4.10, sz: 'sm' },
];

export const CONNECTIONS: [string, string][] = [
  ['ai', 'machine-learning'], ['ai', 'deep-learning'], ['ai', 'nlp'],
  ['ai', 'computer-vision'], ['ai', 'generative-ai'], ['ai', 'llm'],
  ['programming', 'python'], ['programming', 'javascript'],
  ['programming', 'typescript'], ['programming', 'rust'], ['programming', 'go'], ['programming', 'java'],
  ['web', 'react'], ['web', 'nextjs'], ['web', 'nodejs'],
  ['data', 'sql'], ['data', 'mongodb'],
  ['cloud', 'docker'], ['cloud', 'kubernetes'], ['cloud', 'aws'],
  ['devops', 'docker'], ['devops', 'kubernetes'],
  ['machine-learning', 'deep-learning'], ['deep-learning', 'computer-vision'],
  ['deep-learning', 'generative-ai'], ['llm', 'generative-ai'],
  ['javascript', 'typescript'], ['react', 'nextjs'],
  ['llm', 'transformers'], ['llm', 'gpt'], ['transformers', 'gpt'], ['gpt', 'chatgpt'],
  ['deep-learning', 'neural-networks'],
  ['java', 'csharp'], ['java', 'cpp'],
  ['react', 'vue'], ['react', 'svelte'],
  ['sql', 'postgresql'], ['sql', 'redis'], ['mongodb', 'firebase'],
  ['cloud', 'terraform'], ['devops', 'ci-cd'], ['devops', 'github-actions'],
  ['security', 'cryptography'], ['security', 'encryption'], ['security', 'oauth'],
  ['security', 'pen-testing'], ['security', 'zero-trust'],
  ['web', 'http'], ['web', 'html'], ['web', 'css'], ['web', 'tailwind'], ['web', 'dns'],
  ['science', 'physics'], ['science', 'quantum'], ['science', 'biology'],
  ['hardware', 'robotics'], ['hardware', 'iot'], ['hardware', 'embedded'],
  ['design', 'ui-ux'], ['design', 'figma'],
  ['mobile', 'ios'], ['mobile', 'android'], ['mobile', 'react-native'], ['mobile', 'flutter'],
];

// Actual topic keywords — single concepts, no sentences
export const TOPIC_POOL: string[] = [
  'Aeroplane','Engineer','Doctor',"Newton's Laws",'Velocity','Matter','Gravity','Atom','Molecule','Cell','DNA','Vaccine','Virus','Photosynthesis','Electricity','Magnetism','Light','Sound','Energy','Force','Pressure','Friction','Inertia','Momentum','Volcano','Earthquake','Climate','Ocean','Star','Planet','Black Hole','Galaxy','Moon','Water','Air','Metal','Computer','Internet','Robot','Bridge','Building','Car','Train','Soil','Rock','Glass','Wood','Plastic',
];
